# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "exercise-5"
client_id = "55478f3817b9af3748265c3460f573f0"
application_url = "https://crisis-nearby-gravity-arms.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://crisis-nearby-gravity-arms.trycloudflare.com/auth/callback",
  "https://crisis-nearby-gravity-arms.trycloudflare.com/auth/shopify/callback",
  "https://crisis-nearby-gravity-arms.trycloudflare.com/api/auth/callback",
  "https://crisis-nearby-gravity-arms.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "preview-for-checkout.myshopify.com"
