# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "exercise-4"
client_id = "3fd655b647a6762f398c0240c32b4f2f"
application_url = "https://acm-monsters-webcams-drove.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://acm-monsters-webcams-drove.trycloudflare.com/auth/callback",
  "https://acm-monsters-webcams-drove.trycloudflare.com/auth/shopify/callback",
  "https://acm-monsters-webcams-drove.trycloudflare.com/api/auth/callback",
  "https://acm-monsters-webcams-drove.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "preview-for-checkout.myshopify.com"
