# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "exercise-5"
client_id = "74251c3eb825715958583a4a3a23789a"
application_url = "https://uc-predictions-solely-bahrain.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://uc-predictions-solely-bahrain.trycloudflare.com/auth/callback",
  "https://uc-predictions-solely-bahrain.trycloudflare.com/auth/shopify/callback",
  "https://uc-predictions-solely-bahrain.trycloudflare.com/api/auth/callback",
  "https://uc-predictions-solely-bahrain.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://uc-predictions-solely-bahrain.trycloudflare.com/api/proxy"
subpath = "exercise-5"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "preview-for-checkout.myshopify.com"
