# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "demetio-extensions-app"
client_id = "7daa6d2c40b140ed1533f97bf4b34845"
application_url = "https://routes-appointment-offered-situated.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://routes-appointment-offered-situated.trycloudflare.com/auth/callback",
  "https://routes-appointment-offered-situated.trycloudflare.com/auth/shopify/callback",
  "https://routes-appointment-offered-situated.trycloudflare.com/api/auth/callback",
  "https://routes-appointment-offered-situated.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "preview-for-checkout.myshopify.com"
