# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "jp-plus-camp-3-exercise-6"
client_id = "41de07e410f47d98ed6f64c9f66dc081"
application_url = "https://banned-inter-fur-dairy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_fulfillments, write_merchant_managed_fulfillment_orders, write_third_party_fulfillment_orders, write_orders, write_inventory"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://banned-inter-fur-dairy.trycloudflare.com/auth/callback",
  "https://banned-inter-fur-dairy.trycloudflare.com/auth/shopify/callback",
  "https://banned-inter-fur-dairy.trycloudflare.com/api/auth/callback",
  "https://banned-inter-fur-dairy.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jp-plus-camp-3-exercise-6.myshopify.com"
