# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "demetio-products-app"
client_id = "7daa6d2c40b140ed1533f97bf4b34845"
application_url = "https://possession-deemed-indicating-nbc.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://possession-deemed-indicating-nbc.trycloudflare.com/auth/callback",
  "https://possession-deemed-indicating-nbc.trycloudflare.com/auth/shopify/callback",
  "https://possession-deemed-indicating-nbc.trycloudflare.com/api/auth/callback",
  "https://possession-deemed-indicating-nbc.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "data-export-minhnb.myshopify.com"
